// <auto-generated />
namespace MovieRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cliente_MembershipType_Relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cliente_MembershipType_Relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201901302248588_Cliente_MembershipType_Relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
